# Generated by Django 4.2.4 on 2023-08-19 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0002_alter_currency_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyrate',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата сбора данных'),
        ),
    ]
